# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c8c0b0e3b1516dbef5b51c6341b3643678ce6cb487a36af19ed32e52259123ca7d1943383fa95be46ece3126f28e6689692d8634a5a1553bb9185abc2ea1461

test:
  secret_key_base: e35955956689260e8bfb397387dc6911eaa1ab47e3d368b3452d058b1c55f8cf9e674fe186ba1730a2bb27207f2556e0684900c009a7c582dd9fcf0bd0ebcfef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
